# Generated by Django 2.2.5 on 2021-02-02 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210202_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('fashion', 'Fashionable Jewel'), ('Antique', 'Antique Jewel'), ('design', 'Designable Jewel'), ('daily', 'Daily Useable Jewel')], max_length=100),
        ),
    ]
